### PR TITLE
Add help window

### PR DESCRIPTION
**Pull request by fourjay**
Respectfully :-)

Some patches to have a preview window with reminders of all the various key combos

Figured filetype and a separate autoload for the help function keeps this from overloading the primary git manipulation autoload.

FWIW I also added a <nowait> to the the q

### CODE REVIEW

**Comment by idanarye** [comment]
I've checked out your version and tried it out. I think it may conflict with something in my configuration, because the help appears in the wrong window:

screenshot_20160219_020652

At any rate, I'm not so sure an always-on extra window is the way to go. I may have neglected to deal with it for too long, but in ticket #7 @saravanak [copied and modified NERDTree's code](https://github.com/idanarye/vim-merginal/issues/7#issuecomment-166168927), and I prefer his implementation because I find it more comfortable - like anything else they did, NERDTree did this right!

I think I was waiting for @saravanak to create a pull request, he was waiting for me to manually merge his branch, and we both kind of forgot about it... I'll write a comment in ticket #7 to remind him...

I do like the syntax file and the ftplugin though...

**Comment by idanarye** [comment]
Also, please direct PRs to `develop`, not `master`.

**Comment by fourjay** [comment]
I'm glad you are working on a help window. Can't say my code is wonderful, just banged out enough to remove the friction for my own use. I'm sure NerdTree's code is more polished. Among other things managing window splits scenarios seems like it can be non-trivial.

I have splitbelow and splitright set. The help window is a preview window and previewheight=12 (defaultt?). In my setup the merginal window is split's vertical to the right. How does ptag show in your setup?

> I'm not so sure an always-on extra window is the way to go.

That was an afterthought, my original thought was a buffer local ":Help" command. But, thinking about my use case (how do I get immediate use out of this without constant referral to the help and trying to memorize the main commands) it seemed that the window should start as visible. I also did not want to  interfere with your window management. It'd be easy enough to:
* Make it configurable
* Add a close command
* Or conversely add help map key (close to my original approach).
You may want to consider starting it out with an always on, to to help newbies like me :-)

FWIW, I'd suggest adding a filetype to any buffer, as it's a very natural and clean way to augment window behavior for users (a little like user autocommands). I can then drop custom behavior in $VIM/after/ftplugin.

And, looking at my original note, I see that the "nowait" remap got HTMLized away... A lot of the "q" -> quit mappings don't add the nowait (gotta shave those precious seconds).

While looking at this, I thought that buffer local commands for all the operations were a natural interface, i.e.

:merge <tab>
would then autocomplete to 
:Merge normal GMerge no-ff 
and so on. Your command set breaks down by keyword + modifier pretty nicely (Push, Pull, Checkout). I tend to like this approach as it's sort of a TUI menuing system that allows discoverability.

**Comment by idanarye** [comment]
I'm closing this because I ended up implementing my own version.

**Pull request closed without merging**
