### PR TITLE
Minor improvements: clean output

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by idanarye** [comment]
* Removing terminal codes from Git output is a good idea.
* So is making `runGitCommandInTreeReturnResultLines` use `runGitCommandInTreeReturnResult`.
* Using `echom` instead of `echo` might be useful for some cases(e.g. commenting on user actions like `'Branch tracking canceled by the user'`), but doesn't always fit. I certainly don't want to log everything Git spits out, so I'd rather not use it as the default for `runGitCommandInTreeEcho`. I also don't want the prompts(like `'Continue to the next patch(y/n)?'`) to be logged into `:messages`.
* `echo`/`echom` does nothing. `echo ' '` prints an empty line. When only a single line is `echo`ed Vim only prints it at the bottom of the screen without stopping Vim - which means a good chance the user won't notice it - so I add `echo ' '` before it to make Vim print 2 lines and force it to prompt the user to press enter.  
At any rate, these should remain `echo ' '` and not be converted to `echom` because we don't need that empty line in `:messages`.

**Comment by idanarye** [comment]
Looks good, but can you please restore the stars and backticks in the DIFF FILES section in README.md? [It looks really messy on GitHub](https://github.com/blueyed/vim-merginal/tree/improvements#diff-files) without these...

**Comment by blueyed** [comment]
> restore the stars and backticks in the DIFF FILES section

Done. That was a mistake when merging with the doc/ file.

**Comment by idanarye** [comment]
Looks GTG - I just want to checkout&try it before I merged it. I'll try to get to it tonight.

**Comment by idanarye** [comment]
I merged it into develop, but I'm not releasing yet. These changes are too small to justify a release(they are not fixing any annoying bugs(unless you consider the `ggdG` as an annoying bug) and they don't add any new feature), and I already got a new-feature release planned(once I can get myself to work on it, that is...)

**Comment by blueyed** [comment]
Sounds good.

Thanks for reviewing and accepting it, and also for this plugin of course!

**Pull request merged**
